### ISSUE TITLE
Results in Table 1.

### ISSUE THREAD

**Issue by zhaohui-yang** [D-X-Y/TAS#2]
Thanks for sharing the NAS-based method targets at network pruning. After reading the paper, two things make me confusing.

1. About Distillation
From Table 1 and Sec 3.2, the network distillation (KD) seems important for training small models, and this conclusion has also been proved by [1]. I wonder all the results in Table 2 and Table 3 are tuned with KD? Is it a fair comparison with other methods?

2. What is the necessity of the first line in Table 1
As shown in [2], the pruned architecture is essential, rather than the initialize parameters. So is it necessary for putting the results of training from scratch in Table 1? It may achieve comparable results if training with longer steps.

[1] Distilling the Knowledge in a Neural Network
[2] Rethinking the Value of Network Pruning

**Comment by D-X-Y** [comment]
Thanks for your interest.

1. Yes, all results in Table 2 and Table 3 use KD. It is fair since many model acceleration methods use KD, e.g., Cascaded projection: End-to-end network compression and acceleration., CVPR 2019. While we only use the simplest KD approach.

2. It is necessary since our paper should be self-contained, and we also acknowledge [2] in our paper. If longer steps obtain a better result, then it means the model does not converge. However, our model is converged according to validation.

**Comment by zhaohui-yang** [comment]
Thanks for your timely reply,

1. Yes, the latest work cascaded projection introduces a much more complex distillation mechanism some similar to FitNet. However, I think pruning aims at searching the best-performed sub-architecture with the help of a redundant network. Introducing techniques like distillation would be hard to say the final performance gains from the architectures or the distillation techniques. 

2. Maybe the inherited helps.

Thanks~
